
package com.projectfiles.swingcomponents;

import com.projectfiles.model.Model_Menu;
import java.awt.Color;
import java.awt.Graphics;
import java.awt.Graphics2D;
import java.awt.RenderingHints;

/**
 *
 * @author BLANCO
 */
public class MenuItem extends javax.swing.JPanel {

   private boolean selected;
   private boolean hover;
   private final int hand_cursor = 12;
   
    public MenuItem(Model_Menu data) {
        initComponents();
        setOpaque(false);
        
        if(data.getType()==Model_Menu.MenuType.MENU){
            lb_icon.setIcon(data.toIcon());
            lb_name.setText(data.getName());
            lb_icon.setCursor(new java.awt.Cursor(this.hand_cursor));
            lb_name.setCursor(new java.awt.Cursor(this.hand_cursor));
        }
        else if(data.getType()==Model_Menu.MenuType.TITLE){
            lb_icon.setText(data.getName());
            lb_icon.setCursor(new java.awt.Cursor(this.hand_cursor));
            lb_name.setVisible(false);
        }
        else{
            lb_name.setText(" ");
        }
    }

    public void setSelected(boolean selected) {
        this.selected = selected;
        repaint();
    }
    
    public void setHover(boolean hover){
        this.hover = hover;
        repaint();
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lb_icon = new javax.swing.JLabel();
        lb_name = new javax.swing.JLabel();

        lb_icon.setFont(new java.awt.Font("Arial Black", 0, 14)); // NOI18N
        lb_icon.setForeground(new java.awt.Color(255, 255, 255));

        lb_name.setForeground(new java.awt.Color(255, 255, 255));
        lb_name.setText("Menu Name");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(lb_icon)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lb_name, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(33, 33, 33))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lb_icon, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lb_name, javax.swing.GroupLayout.DEFAULT_SIZE, 33, Short.MAX_VALUE))
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

   @Override
    protected void paintComponent(Graphics grphcs){
        if(selected || hover){
            Graphics2D g2 = (Graphics2D) grphcs;
            g2.setRenderingHint(RenderingHints.KEY_ANTIALIASING,RenderingHints.VALUE_ANTIALIAS_ON);
            if(selected){
               g2.setColor(new Color(255,255,255,80)); 
            }
            else{
                g2.setColor(new Color(255,255,255,30));
            }
            g2.fillRoundRect(2, 0, getWidth(), getHeight(), 10, 10);
        }
        super.paintComponent(grphcs);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel lb_icon;
    private javax.swing.JLabel lb_name;
    // End of variables declaration//GEN-END:variables
}
